### ISSUE TITLE
bitOffset parser in BitRange doesn't handle hex numbers

### ISSUE THREAD

**Issue by pinealservo** [japaric/svd#31]
In parsing a SVD from TI for their ARM-based MSP432 line, I got a panic in svd2rust when it came across bitRange elements with hex-valued offsets and lengths, e.g. "0x3".

According to the SVD schema, these are supposed to be *scaledNonNegativeInteger* values, and those are supposed to be acceptable as decimal, hex, or binary; they apparently also support a unit suffix. Here's the pattern from the schema: "[+]?(0x|0X|#)?[0-9a-fA-F]+[kmgtKMGT]?"

A quick look through the lib.rs source shows a lot of uses of the core from_str implementation for u32; I haven't checked yet how many of them are meant to be *scaledNonNegativeInteger* values, but I suspect there are more than the bitRange ones that ought to be switched over to parser::u32.

**Comment by japaric** [comment]
Fixed in #32.
