### ISSUE TITLE
<dim> can have hexadecimal values

### ISSUE THREAD

**Issue by wez** [japaric/svd#57]
Running svd2rust on this svd:

https://raw.githubusercontent.com/particle-iot/nrf5_sdk/master/modules/nrfx/mdk/nrf52840.svd

yields a panic because this code:

```
impl RegisterClusterArrayInfo {
    fn parse(tree: &Element) -> RegisterClusterArrayInfo {
        RegisterClusterArrayInfo {
            dim: try!(tree.get_child_text("dim").unwrap().parse::<u32>()),
```

doesn't know how to parse the hexadecimal values in that file.

I know that there's a refactoring happening, so I'll just stick this little diff here that allowed me to get through generating code for this file:

```
$ git diff
diff --git a/src/lib.rs b/src/lib.rs
index 88dc43e..949d7de 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -391,7 +391,9 @@ impl RegisterInfo {
 impl RegisterClusterArrayInfo {
     fn parse(tree: &Element) -> RegisterClusterArrayInfo {
         RegisterClusterArrayInfo {
-            dim: try!(tree.get_child_text("dim").unwrap().parse::<u32>()),
+            dim: try!(tree.get_child("dim").map(|t| {
+                try!(parse::u32(t))
+            })),
             dim_increment: try!(tree.get_child("dimIncrement").map(|t| {
                 try!(parse::u32(t))
             })),
```

**Comment by Emilgardis** [comment]
Fixed after/in refactor. https://github.com/japaric/svd/blob/9d87a7b407830726430fcc7afddb8a19ae88ef8c/src/svd/registerclusterarrayinfo.rs#L28 https://github.com/japaric/svd/blob/9d87a7b407830726430fcc7afddb8a19ae88ef8c/src/types.rs#L26-L59
