### ISSUE TITLE
Should register description should be optional?

### ISSUE THREAD

**Issue by evq** [japaric/svd#59]
I recently ran into an SVD that has single tag empty descriptions for a few register clusters (ATSAML11). It seems like that is [against the SVD spec](http://www.keil.com/pack/doc/CMSIS/SVD/html/svd_xml_conventions_gr.html#_), so I manually removed the tag entirely. Unfortunately that still doesn't parse correctly, as the description field is currently required.

If I'm reading http://www.keil.com/pack/doc/CMSIS/SVD/html/elem_registers.html correctly though it sounds like the description field should be optional.

**Comment by Emilgardis** [comment]
The register description is indeed optional according to the spec

```xml
<xs:complexType name="registerType">
[...]
<xs:element name="description" type="stringType" minOccurs="0"/>
[...]
</xs:complexType>
```

Interestingly enough the only non-optional description field is in clusters.

Thanks for reporting it.
